import { themeCss } from "./tokens.js";

/**
 * The stylesheet the patched AgentOffice UI loads (`office/theme/agent-office.css`, copied into the vendored UI by
 * `npm run office:setup`): the Agent Office tokens plus the HUD classes the patch uses. Generated, never edited by
 * hand: `npm run office:theme` rewrites it and a test fails when it drifts.
 */
const HUD_CSS = `
html, body { background: var(--bg); color: var(--text-primary); font: var(--type-body); }
:focus-visible { outline: none; box-shadow: var(--shadow-focus); }
.ao-brand { position: absolute; bottom: 20px; left: 20px; z-index: 10; display: flex; flex-direction: column; padding: var(--space-3) var(--space-4); background: var(--panel-bg); border: 1px solid var(--panel-border); border-radius: var(--radius-md); box-shadow: var(--shadow-panel); }
.ao-eyebrow, .ao-caption { font: var(--type-caption); color: var(--text-muted); }
.ao-title { margin: 0; font: var(--type-page-title); }
.ao-panel { position: absolute; overflow: hidden; background: var(--panel-bg); color: var(--text-primary); border: 1px solid var(--panel-border); border-radius: var(--radius-md); box-shadow: var(--shadow-panel); }
.ao-panel-head { display: flex; align-items: center; justify-content: space-between; gap: var(--space-2); padding: var(--space-2) var(--space-3); cursor: grab; border-bottom: 1px solid var(--panel-raised); }
.ao-panel-head.is-min { border-bottom: 0; }
.ao-panel-title { margin: 0; font: var(--type-room-title); font-size: 16px; line-height: 20px; }
.ao-panel-sub { font: var(--type-caption); color: var(--text-muted); }
.ao-panel-body { padding: var(--space-3); }
.ao-btn { display: inline-flex; align-items: center; justify-content: center; gap: var(--space-2); min-height: 32px; padding: 0 var(--space-3); background: transparent; color: var(--text-primary); border: 1px solid var(--panel-border); border-radius: var(--radius-md); font: var(--type-label); cursor: pointer; }
.ao-btn:hover { border-color: var(--text-secondary); }
.ao-btn-primary { background: var(--accent-primary); border-color: var(--accent-primary); color: var(--on-fill); box-shadow: var(--shadow-pixel); }
.ao-icon-btn { width: 32px; padding: 0; }
.ao-field { width: 100%; min-height: 32px; padding: 0 var(--space-2); background: var(--bg); color: var(--text-primary); border: 1px solid var(--panel-border); border-radius: var(--radius-md); font: var(--type-label); font-weight: 400; }
.ao-taskboard { left: 20px; top: 20px; width: 300px; max-height: 50vh; display: flex; flex-direction: column; gap: var(--space-3); padding: var(--space-4); z-index: 10; }
.ao-form { display: flex; flex-direction: column; gap: var(--space-2); }
.ao-row { display: flex; gap: var(--space-2); }
.ao-row > select { flex: 1; }
.ao-tasks { flex: 1; overflow-y: auto; display: flex; flex-direction: column; gap: var(--space-1); margin: 0; padding: 0; list-style: none; }
.ao-task { display: flex; flex-direction: column; gap: 4px; padding: var(--space-2); background: var(--panel-raised); border-radius: var(--radius-sm); }
.ao-task-title { font: var(--type-label); overflow-wrap: anywhere; }
.ao-task-meta { display: flex; align-items: center; gap: var(--space-2); font: var(--type-caption); color: var(--text-muted); }
.ao-empty { margin: 0; font: var(--type-caption); color: var(--text-muted); }
.ao-foot { display: flex; flex-direction: column; gap: 2px; padding-top: var(--space-2); border-top: 1px solid var(--panel-raised); font: var(--type-timestamp); color: var(--text-muted); }
.ao-badge { --c: var(--state-idle); display: inline-flex; align-items: center; gap: 6px; padding: 1px 6px; border: 2px solid var(--c); border-radius: var(--radius-sm); background: var(--c); color: var(--on-fill); font: var(--type-status); letter-spacing: var(--type-status-tracking); text-transform: uppercase; white-space: nowrap; }
.ao-badge svg { flex: none; }
.ao-badge.s-queued { --c: var(--state-idle); background: transparent; color: var(--c); }
.ao-badge.s-working { --c: var(--state-working); }
.ao-badge.s-completed { --c: var(--state-completed); }
.ao-badge.s-blocked { --c: var(--state-blocked); }
.ao-badge.s-failed { --c: var(--state-failed); }
.ao-chip-readonly { --c: var(--offline); background: transparent; color: var(--c); border-style: dashed; border-width: 1px; }
@media (prefers-reduced-motion: reduce) { * { transition: none !important; animation: none !important; } }
`;

export function officeThemeCss(): string {
  return `/* Agent Office theme for the patched AgentOffice UI. Generated by \`npm run office:theme\` from src/theme; do not edit. */\n${themeCss()}${HUD_CSS}`;
}
